### ISSUE TITLE
ошибка

### ISSUE THREAD

**Issue by kinlok951** [Tephida/vii#38]
{"title":"\u0421\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u0430\u044f \u0441\u0435\u0442\u044c","user_pm_num":"","new_news":"","new_ubm":"","gifts_link":"\/balance","support":"","news_link":"","demands":"","new_photos":"","new_photos_link":"1","requests_link":"","new_groups":"","new_groups_lnk":"\/groups","sbar":"","content":"
пытаюсь вот этот шаблон поставить и вот такая фигня вылазит

$spBar = $spBar ?? null; не помогает 

вот от этой сборки https://cmstools.ru/topic/1245-сборка-friendes-2019г/

**Comment by semyon492** [comment]
В шаблоне в page. Go() должно быть json
