### ISSUE TITLE
можете сделать вот это для этай сборки ?

### ISSUE THREAD

**Issue by kinlok951** [Tephida/vii#7]
https://xdan.ru/sistema-dialogov-na-php-kak-v-v-kontakte.html только без веб сокета и ланг полинга

**Comment by semyon492** [comment]
Позже сделаю

**Comment by kinlok951** [comment]
а вкокой версии будет обновление диалогов ?

**Comment by semyon492** [comment]
Как только, так сразу

**Comment by kinlok951** [comment]
понятно

**Comment by kinlok951** [comment]
> Как только, так сразу

так бы и написал что не буду реализовывать да ивсе

**Comment by semyon492** [comment]
Вопрос еще открыт.

**Comment by semyon492** [comment]
**Исправь свои грамматические ошибки**

**Comment by kinlok951** [comment]
спасибо огромное сейчас можно и что то делать на этом движке

**Comment by semyon492** [comment]
@kinlok951 в [xdan/xddialogs](https://github.com/xdan/xddialogs): 

- две лишние таблицы **pfx_message_to_user** и **pfx_user_to_dialog**
- также как и здесь вместо вебсокета используются AJAX запросы для проверки новых сообщений(2-3 сек.)

Зачем id диалога переименовывать в hash?

**Comment by kinlok951** [comment]
в каком файле подключение файл Dialog.php

**Comment by semyon492** [comment]
Добавлен и в сообщениях пока не используется.

**Comment by kinlok951** [comment]
понятно

**Comment by kinlok951** [comment]
если так к примеру 
Перед отправкой письма сделать задержку.

// ждать 1 секунду
usleep(1000000);




Пример #1 Пример использования usleep()

<?php

// Текущее время
echo date('h:i:s') . "\n";

// ждать 2 секунды
usleep(2000000);

// вернуться к исполнению
echo date('h:i:s') . "\n";

?>
Результат выполнения данного примера:

11:13:28
11:13:30

**Comment by semyon492** [comment]
> если так к примеру Перед отправкой письма сделать задержку.
> 
> // ждать 1 секунду usleep(1000000);
> 
> Пример #1 Пример использования usleep()
> 
> php
> 
> // Текущее время echo date('h:i:s') . "\n";
> 
> // ждать 2 секунды usleep(2000000);
> 
> // вернуться к исполнению echo date('h:i:s') . "\n";
> 
> ?> Результат выполнения данного примера:
> 
> 11:13:28 11:13:30

Не убедительно

**Comment by semyon492** [comment]
Диалоги используются #32
